# Generated by Django 3.2.15 on 2023-06-08 21:31

from django.db import migrations


def create_data(apps, schema_editor):
    Student = apps.get_model('api', 'Student')
    Student(name="Joe Silver", email="joe@email.com",
            document="22342342", phone="00000000").save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
