# Generated by Django 3.2.15 on 2023-06-23 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_huesped_hospedador'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedador',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
