# Generated by Django 3.2.15 on 2023-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hospedador_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospedador',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
