# Generated by Django 3.2.15 on 2023-06-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_hospedador_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospedador',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='hospedador',
            name='guests',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
